name: CI

on:
  push:
    branches:
      - main

jobs:
  zap_scan:
    permissions: write-all
    runs-on: ubuntu-latest
    name: OWASP ZAP Baseline Scan of Contact List App
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: "https://thinking-tester-contact-list.herokuapp.com/"
          artifact_name: "zap_report.html"
          